-- 创建地区表
CREATE TABLE IF NOT EXISTS `regions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenantId` int(11) NOT NULL,
  `code` varchar(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `level` int(11) NOT NULL,
  `parentCode` varchar(20) DEFAULT NULL,
  `parentId` int(10) unsigned DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `regions_code_unique` (`code`),
  KEY `regions_parent_code_index` (`parentCode`),
  KEY `regions_level_index` (`level`),
  KEY `regions_tenant_id_level_index` (`tenantId`, `level`),
  KEY `regions_parent_id_foreign` (`parentId`),
  CONSTRAINT `regions_parent_id_foreign` FOREIGN KEY (`parentId`) REFERENCES `regions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `regions_tenant_id_foreign` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 插入基础数据（省级）
INSERT INTO `regions` (`tenantId`, `code`, `name`, `level`, `parentCode`, `parentId`, `createdAt`, `updatedAt`) VALUES
(1, '110000', '北京市', 1, NULL, NULL, NOW(), NOW()),
(1, '120000', '天津市', 1, NULL, NULL, NOW(), NOW()),
(1, '130000', '河北省', 1, NULL, NULL, NOW(), NOW()),
(1, '140000', '山西省', 1, NULL, NULL, NOW(), NOW()),
(1, '150000', '内蒙古自治区', 1, NULL, NULL, NOW(), NOW()),
(1, '210000', '辽宁省', 1, NULL, NULL, NOW(), NOW()),
(1, '220000', '吉林省', 1, NULL, NULL, NOW(), NOW()),
(1, '230000', '黑龙江省', 1, NULL, NULL, NOW(), NOW()),
(1, '310000', '上海市', 1, NULL, NULL, NOW(), NOW()),
(1, '320000', '江苏省', 1, NULL, NULL, NOW(), NOW()),
(1, '330000', '浙江省', 1, NULL, NULL, NOW(), NOW()),
(1, '340000', '安徽省', 1, NULL, NULL, NOW(), NOW()),
(1, '350000', '福建省', 1, NULL, NULL, NOW(), NOW()),
(1, '360000', '江西省', 1, NULL, NULL, NOW(), NOW()),
(1, '370000', '山东省', 1, NULL, NULL, NOW(), NOW()),
(1, '410000', '河南省', 1, NULL, NULL, NOW(), NOW()),
(1, '420000', '湖北省', 1, NULL, NULL, NOW(), NOW()),
(1, '430000', '湖南省', 1, NULL, NULL, NOW(), NOW()),
(1, '440000', '广东省', 1, NULL, NULL, NOW(), NOW()),
(1, '450000', '广西壮族自治区', 1, NULL, NULL, NOW(), NOW()),
(1, '460000', '海南省', 1, NULL, NULL, NOW(), NOW()),
(1, '500000', '重庆市', 1, NULL, NULL, NOW(), NOW()),
(1, '510000', '四川省', 1, NULL, NULL, NOW(), NOW()),
(1, '520000', '贵州省', 1, NULL, NULL, NOW(), NOW()),
(1, '530000', '云南省', 1, NULL, NULL, NOW(), NOW()),
(1, '540000', '西藏自治区', 1, NULL, NULL, NOW(), NOW()),
(1, '610000', '陕西省', 1, NULL, NULL, NOW(), NOW()),
(1, '620000', '甘肃省', 1, NULL, NULL, NOW(), NOW()),
(1, '630000', '青海省', 1, NULL, NULL, NOW(), NOW()),
(1, '640000', '宁夏回族自治区', 1, NULL, NULL, NOW(), NOW()),
(1, '650000', '新疆维吾尔自治区', 1, NULL, NULL, NOW(), NOW());