// 对应 sequelize DataTypes 的所有类型
export const ColumnDataTypes = {
  ID: "ID",
  DOCNO: "DOCNO",
  DATENUMBER: "DATENUMBER",
  DATE: 'DATE',
  DATETIME: 'DATE',
  DATERANGE: 'JSON',
  QTY: 'QTY',
  AMT: 'AMT',
  STRING: 'STRING',
  ENUM: 'ENUM',
  TEXT: 'TEXT',
  JSON: 'JSON',
  REGION: 'JSON',
  INTEGER: 'INTEGER',
  BOOLEAN: 'BOOLEAN',
  DECIMAL: 'DECIMAL',
  BIGINT: 'BIGINT',
  VIRTUAL: 'VIRTUAL',
};